module.exports = [
    {
      "EVENTID": 1478,
      "EVENTNAME": "Richmond vs. Carlton",
      "DESCR": "Carpark closed to public. Staff Disability & emergency services only. Carpark Gate 3 Closed 8pm Carpark Gate 5 Not Open Carpark Gate 6 Not Open Carpark Gate 7 Not Open Light Towers on at 18:25 Light Towers off at 23:05 Game Finished 22:11",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "25:00.2",
      "DAYID": 7,
      "YEARID": 24,
      "WEATHERTEMP": 23.6,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 9,
      "VENUEID": 1,
      "ATTENDANCEID": 994,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 3,
      "TOTALATT": 90151,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 90000,
      "FINBUDGATT": 90000,
      "EventNameDate": "Richmond vs. Carlton - 2018-03-22 0",
      "EventMonth": "March",
      "EventDay": 22,
      "EventYearName": 2018,
      "FinancialYear": 2018,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1479,
      "EVENTNAME": "Hawthorn vs. Collingwood",
      "DESCR": "Carpark capacity reduced by 10% at 3pm Carpark Gate 2 Closed 20:15 Carpark Gate 5 Closed 20:30 Carpark Gate 6 Closed 20:00 Carpark Gate 7 Closed 20:15 Supplementary Lights on at 17:30 Light Towers on at 18:25 Light Towers off at 22:50 Game Finished 22:04",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "25:00.8",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 20.2,
      "WEATHERRAIN": 13,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 995,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 8,
      "AWAYTEAMID": 4,
      "TOTALATT": 58051,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 64000,
      "FINBUDGATT": 64000,
      "EventNameDate": "Hawthorn vs. Collingwood - 2018-03-24 0",
      "EventMonth": "March",
      "EventDay": 24,
      "EventYearName": 2018,
      "FinancialYear": 2018,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1480,
      "EVENTNAME": "Melbourne vs. Geelong Cats",
      "DESCR": "Carpark Gate 3 Closed 14:40 Carpark Gate 5 Closed 15:45 Carpark Gate 6 Closed 15:20 Carpark Gate 7 Closed 16:30 Light Towers on at 17:40 Light Towers off at 18:30 Game Finished 18:02",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.4",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 23.9,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 15,
      "VENUEID": 1,
      "ATTENDANCEID": 996,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 7,
      "TOTALATT": 54112,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 51000,
      "FINBUDGATT": 51000,
      "EventNameDate": "Melbourne vs. Geelong Cats - 2018-03-25 0",
      "EventMonth": "March",
      "EventDay": 25,
      "EventYearName": 2018,
      "FinancialYear": 2018,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1481,
      "EVENTNAME": "Collingwood vs. GWS Giants",
      "DESCR": "Carpark Gate 3 Closed 17:20 Carpark Gate 5 Closed 17:40 Carpark Gate 6 Closed 16:55 Carpark Gate 7 Closed 15:20 Supplementary Lights on at 18:00 Light Towers on at 18:00 Light Towers off at 19:55 Game Finished at 19:20",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "35:00.8",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 20.3,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 997,
      "DAYNIGHTID": 3,
      "MatchTimeName": "Twilight",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 41,
      "TOTALATT": 30941,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 27000,
      "FINBUDGATT": 27000,
      "EventNameDate": "Collingwood vs. GWS Giants - 2018-03-31 0",
      "EventMonth": "March",
      "EventDay": 31,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1482,
      "EVENTNAME": "Geelong Cats vs. Hawthorn",
      "DESCR": "Carpark Gate 3 Closed 14:35 Carpark Gate 5 Closed 14:45 Carpark Gate 6 Closed 14:28 Carpark Gate 7 Closed 16:30 Supplementary Lights on at 16:32 Light Towers on at 16:32 Light Towers off at 18:50 Game Finished 18:04",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.7",
      "DAYID": 4,
      "YEARID": 24,
      "WEATHERTEMP": 19.4,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 9,
      "VENUEID": 1,
      "ATTENDANCEID": 998,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 7,
      "AWAYTEAMID": 8,
      "TOTALATT": 73189,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 60000,
      "FINBUDGATT": 60000,
      "EventNameDate": "Geelong Cats vs. Hawthorn - 2018-04-02 0",
      "EventMonth": "April",
      "EventDay": 2,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1483,
      "EVENTNAME": "Carlton vs. Collingwood",
      "DESCR": "Television: 7mate Live Car Park Gate 3: 19:33 Car Park Gate 5: 19:30 Car Park Gate 6: 19:20 Car Park Gate 7: 19:50 Supplementary Lights On: 17:30 Light Towers On: 18:30 Light Towers Off: 23:00 Game finished: 22:27",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.8",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 15.2,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 4,
      "VENUEID": 1,
      "ATTENDANCEID": 999,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 3,
      "AWAYTEAMID": 4,
      "TOTALATT": 68548,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 68000,
      "FINBUDGATT": 68000,
      "EventNameDate": "Carlton vs. Collingwood - 2018-04-06 0",
      "EventMonth": "April",
      "EventDay": 6,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1484,
      "EVENTNAME": "Melbourne vs. North Melbourne",
      "DESCR": "Round 3   7th April 2018 Game Over :- 4:48 pm Attendance :- 35518 Broadcaster:- Fox Sports 3 Live Supps on :- 4:30 PM Towers -Not used Car Parks Gate 3 Close 13:45 Gate 5 Close at 14:00 Gate 7 Close at 13:30 Gate 7 Close at 12:25 Curtainraiser:- 11:05 am                          Aust U18     17-12-114 defeated North Melbourne  10 11- 71",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.5",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 19.5,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 0,
      "VENUEID": 1,
      "ATTENDANCEID": 1000,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 9,
      "TOTALATT": 35518,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 36000,
      "FINBUDGATT": 36000,
      "EventNameDate": "Melbourne vs. North Melbourne - 2018-04-07 0",
      "EventMonth": "April",
      "EventDay": 7,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1485,
      "EVENTNAME": "Richmond vs. Hawthorn",
      "DESCR": "Car Park Gate 3 closed 12:16hrs Car Park Gate 5 closed 12:30hrs Car Park Gate 6 closed 12:16hrs Car Park Gate 7 closed 13:00hrs Towers not turned on. Game over 15:48hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.6",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 28.5,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 201,
      "VENUEID": 1,
      "ATTENDANCEID": 1001,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 8,
      "TOTALATT": 70701,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 72000,
      "FINBUDGATT": 72000,
      "EventNameDate": "Richmond vs. Hawthorn - 2018-04-08 0",
      "EventMonth": "April",
      "EventDay": 8,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1486,
      "EVENTNAME": "Richmond vs. Brisbane Lions",
      "DESCR": "Carpark Gate 3 Closed 13:35 Carpark Gate 5 Closed 13:50 Carpark Gate 6 Closed 13:29 Carpark Gate 7 Closed 15:00 Supps On 13:30 Light Towers On 13:30 Light Towers Off 17:05 Game Finished 16:32",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.7",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 13.1,
      "WEATHERRAIN": 12,
      "WEATHERWIND": 18,
      "VENUEID": 1,
      "ATTENDANCEID": 1002,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 2,
      "TOTALATT": 32870,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 42000,
      "FINBUDGATT": 42000,
      "EventNameDate": "Richmond vs. Brisbane Lions - 2018-04-14 0",
      "EventMonth": "April",
      "EventDay": 14,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1487,
      "EVENTNAME": "Hawthorn vs. Melbourne",
      "DESCR": "Car Park capacity reduced to 60% as at 12:17hrs Car Park Gate 3 closed 14:55hrs Car Park Gate 5 closed 14:35hrs Car Park Gate 6 closed 14:10hrs Car Park Gate 7 closed 15:10hrs Supplementary lights on 14:30hrs Light Towers on 14:30hrs Light Towers off 18:30hrs Kick to Kick cancelled due weather Game over 18:02hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.2",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 16.9,
      "WEATHERRAIN": 3,
      "WEATHERWIND": 8,
      "VENUEID": 1,
      "ATTENDANCEID": 1003,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 8,
      "AWAYTEAMID": 10,
      "TOTALATT": 41973,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 50000,
      "FINBUDGATT": 50000,
      "EventNameDate": "Hawthorn vs. Melbourne - 2018-04-15 0",
      "EventMonth": "April",
      "EventDay": 15,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1488,
      "EVENTNAME": "Carlton vs. West Coast Eagles",
      "DESCR": "Car Park Gate 3 closed 17:20hrs Car Park Gate 5 closed 16:17hrs Car Park Gate 6 closed 16:50hrs Car Park Gate 7 closed 17:15hrs Supplementary lights on 16:00hrs Light Towers on 16:00hrs Light Towers off 19:45hrs Game over 19:12hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "35:00.7",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 17.3,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 7,
      "VENUEID": 1,
      "ATTENDANCEID": 1004,
      "DAYNIGHTID": 3,
      "MatchTimeName": "Twilight",
      "HOMETEAMID": 3,
      "AWAYTEAMID": 15,
      "TOTALATT": 27900,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 26000,
      "FINBUDGATT": 26000,
      "EventNameDate": "Carlton vs. West Coast Eagles - 2018-04-21 0",
      "EventMonth": "April",
      "EventDay": 21,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1489,
      "EVENTNAME": "Melbourne vs. Richmond",
      "DESCR": "Carparks Closed to public, Staff, Disability Media, Passholders and Emergency services only Carpark Gate 3 Closed 20:00 Carpark Gate 5 Closed  Carpark Gate 6 Closed Carpark Gate 7 Closed Supplimentary lights on at 17:00 Light towers on at 19:15 Light towers off at 23:00 Game Finished 22:03",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "25:00.0",
      "DAYID": 5,
      "YEARID": 24,
      "WEATHERTEMP": 19.5,
      "WEATHERRAIN": 1,
      "WEATHERWIND": 7,
      "VENUEID": 1,
      "ATTENDANCEID": 1005,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 12,
      "TOTALATT": 77071,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 87000,
      "FINBUDGATT": 87000,
      "EventNameDate": "Melbourne vs. Richmond - 2018-04-24 0",
      "EventMonth": "April",
      "EventDay": 24,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1490,
      "EVENTNAME": "Collingwood vs. Essendon",
      "DESCR": "Carparks Closed to Public. Staff, Disabled Media and Pass holders only. Carpark Gate 3 Closed 16:00 Carpark Gate 5 Closed Carpark Gate 6 Closed Carpark Gate 7 Closed Supplementary lights on at 14:30 Light Towers on at 14:30 Light Towers off at 18:30 Game Finished 17:51",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.4",
      "DAYID": 6,
      "YEARID": 24,
      "WEATHERTEMP": 18.8,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 8,
      "VENUEID": 1,
      "ATTENDANCEID": 1006,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 5,
      "TOTALATT": 91440,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 93000,
      "FINBUDGATT": 93000,
      "EventNameDate": "Collingwood vs. Essendon - 2018-04-25 0",
      "EventMonth": "April",
      "EventDay": 25,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1491,
      "EVENTNAME": "Collingwood vs. Richmond",
      "DESCR": "Carpark Gate 3 Closed 15:00 Carpark Gate 5 Closed 14:55 Carpark Gate 6 Closed 14:45 Carpark Gate 7 Closed 16:15 Supplementary Lights on at 16:30 Light towers on at 16:30 Light towers off at 18:45 Game Finished 17:55",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.8",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 17,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 1007,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 12,
      "TOTALATT": 72157,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 78000,
      "FINBUDGATT": 78000,
      "EventNameDate": "Collingwood vs. Richmond - 2018-04-29 0",
      "EventMonth": "April",
      "EventDay": 29,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1492,
      "EVENTNAME": "Essendon vs. Hawthorn",
      "DESCR": "Carpark Gate 3 Closed 14:05 Carpark Gate 5 Closed 14:56 Carpark Gate 6 Closed 13:40 Carpark Gate 7 Closed 14:20 Supplementary Lights on 13:50 Light Towers on at 16:05 Light Towers off at 17:15 Game Finished 16:39",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.8",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 19.9,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 9,
      "VENUEID": 1,
      "ATTENDANCEID": 1008,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 5,
      "AWAYTEAMID": 8,
      "TOTALATT": 53018,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 50000,
      "FINBUDGATT": 50000,
      "EventNameDate": "Essendon vs. Hawthorn - 2018-05-05 0",
      "EventMonth": "May",
      "EventDay": 5,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1493,
      "EVENTNAME": "Richmond vs. Fremantle",
      "DESCR": "Carpark Gate 3 Closed 12:40 Carpark Gate 5 Closed 12:44 Carpark Gate 6 Closed 11:50 Carpark Gate 7 Closed 14:00 Light towers not used Game Finished 15:43",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.4",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 20.4,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 1009,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 6,
      "TOTALATT": 43240,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 35000,
      "FINBUDGATT": 35000,
      "EventNameDate": "Richmond vs. Fremantle - 2018-05-06 0",
      "EventMonth": "May",
      "EventDay": 6,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1494,
      "EVENTNAME": "Hawthorn vs. Sydney Swans",
      "DESCR": "Carpark Closed for All Patrons due to rain Carpark Gate 3 Closed Carpark Gate 5 Closed Carpark Gate 6 Closed Carpark Gate 7 Closed Supplementary lights on at 17:30 Light Towers on at 19:30 Light Towers off at 23:00 Game Finished 22:19",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.3",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 14.7,
      "WEATHERRAIN": 8,
      "WEATHERWIND": 21,
      "VENUEID": 1,
      "ATTENDANCEID": 1010,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 8,
      "AWAYTEAMID": 14,
      "TOTALATT": 32784,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 40000,
      "FINBUDGATT": 40000,
      "EventNameDate": "Hawthorn vs. Sydney Swans - 2018-05-11 0",
      "EventMonth": "May",
      "EventDay": 11,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1495,
      "EVENTNAME": "Carlton vs. Essendon",
      "DESCR": "Car Park reduced capacity 50% due rain previous day.  1000 spots Car Park Gate 3 closed 14:45hrs Car Park Gate 5 closed 13:55hrs Car Park Gate 6 closed 14:10hrs Car Park Gate 7 closed 15:00hrs Supps on 13:25hrs Light Towers on 15:55hrs Light Towers off 17:25hrs Game over 16:48hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.6",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 15.7,
      "WEATHERRAIN": 17,
      "WEATHERWIND": 0,
      "VENUEID": 1,
      "ATTENDANCEID": 1011,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 3,
      "AWAYTEAMID": 5,
      "TOTALATT": 44669,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 44000,
      "FINBUDGATT": 44000,
      "EventNameDate": "Carlton vs. Essendon - 2018-05-12 0",
      "EventMonth": "May",
      "EventDay": 12,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1496,
      "EVENTNAME": "Collingwood vs. Geelong Cats",
      "DESCR": "Round 8 - Collingwood v Geelong May 13 2018 Game Finish :- 17.45 Broadcaster : Channel 7 Live Supps 16.35 Towers:- On 16.35              Off  18.30 Car Park - 90% capacity  Gate 3 closed :- 16.10 Gate 5 Closed :- 16.10 Gate 6 Closed:-  15.50 Gate 7 Closed:-   16.30 Attendance:- 44602",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.7",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 15,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 13,
      "VENUEID": 1,
      "ATTENDANCEID": 1012,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 7,
      "TOTALATT": 44602,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 54000,
      "FINBUDGATT": 54000,
      "EventNameDate": "Collingwood vs. Geelong Cats - 2018-05-13 0",
      "EventMonth": "May",
      "EventDay": 13,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1497,
      "EVENTNAME": "Essendon vs. Geelong Cats",
      "DESCR": "Curtain Raiser AFL Victoria Country Championship Ballarat FC 16-10-106 lost to Goulburn Valley 20-8-128. Carpark Gate 3 Closed 15:55 (Mobility impaired only) Carpark Gate 5 Closed 17:30 Carpark Gate 6 Closed 17:00 Carpark Gate 7 Closed 16:05 Supplementary Lights 13:50 Light Towers on at 16:33 Light Towers off at 19:50 Game Finished 19:02",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "35:00.7",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 13.8,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 7,
      "VENUEID": 1,
      "ATTENDANCEID": 1013,
      "DAYNIGHTID": 3,
      "MatchTimeName": "Twilight",
      "HOMETEAMID": 5,
      "AWAYTEAMID": 7,
      "TOTALATT": 50228,
      "EVENTCATEGORYID": 3,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 49000,
      "FINBUDGATT": 49000,
      "EventNameDate": "Essendon vs. Geelong Cats - 2018-05-19 0",
      "EventMonth": "May",
      "EventDay": 19,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1498,
      "EVENTNAME": "Carlton vs. Melbourne",
      "DESCR": "Carpark Gate 3 Closed: 12:30 Carpark Gate 5 Closed: 12:47 Carpark Gate 6 Closed: 12:38 Carpark Gate 7 Closed: 13:50 Supplementary Lights On: 12.45 Light Towers On: 13:37 Light Towers Off: 16:10 Game Finished: 15:45",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.7",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 15.7,
      "WEATHERRAIN": 2,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 1014,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 3,
      "AWAYTEAMID": 10,
      "TOTALATT": 44122,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 45000,
      "FINBUDGATT": 45000,
      "EventNameDate": "Carlton vs. Melbourne - 2018-05-20 0",
      "EventMonth": "May",
      "EventDay": 20,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1499,
      "EVENTNAME": "Richmond vs. St Kilda",
      "DESCR": "Round 10   Saturday May 26 2018 Game Finish:- 4:18pm Broadcaster:- Fox Footy Live Supps:- 3:31 pm Towers:- Not Used Car Parks:-  Gate 3 Closed  1:40pm Gate 5 Closed  1:15pm Gate 6 Closed   1:00pm Gate 7 Closed :- 2:05pm",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "45:00.6",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 18.5,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 17,
      "VENUEID": 1,
      "ATTENDANCEID": 1015,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 13,
      "TOTALATT": 48850,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 52000,
      "FINBUDGATT": 52000,
      "EventNameDate": "Richmond vs. St Kilda - 2018-05-26 0",
      "EventMonth": "May",
      "EventDay": 26,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1500,
      "EVENTNAME": "Essendon vs. Richmond",
      "DESCR": "Curtain Raiser Rio Tinto Cup Hill Team 5-10-40 lost to Dempsey Team 11-9-75 Carparks Closed to public Passholders and Emergency only Carpark Gate 3 Closed 20:30 Carpark Gate 5 Not open Carpark Gate 6 Not open Carpark Gate 7 Not open Supplementary Lights on at 15:55 Light Towers on at 18:57 Light Towers off at 22:45 Game Finished 21:55",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "25:00.6",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 9.8,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 3,
      "VENUEID": 1,
      "ATTENDANCEID": 1016,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 5,
      "AWAYTEAMID": 12,
      "TOTALATT": 81046,
      "EVENTCATEGORYID": 3,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 86000,
      "FINBUDGATT": 86000,
      "EventNameDate": "Essendon vs. Richmond - 2018-06-02 0",
      "EventMonth": "June",
      "EventDay": 2,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1501,
      "EVENTNAME": "Collingwood vs. Fremantle",
      "DESCR": "Car Park Gate 3 closed at: 16:00 Car Park Gate 5 closed at: 16:10 Car Park Gate 6 closed at: 15:08 Car Park Gate 7 closed at: 16:10 Supplementary Lights on at 15:00 Light towers on at 15:00 Light towers off at 18:30 Game Finished at 17:57",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.1",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 12.9,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 7,
      "VENUEID": 1,
      "ATTENDANCEID": 1017,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 6,
      "TOTALATT": 34542,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 37000,
      "FINBUDGATT": 37000,
      "EventNameDate": "Collingwood vs. Fremantle - 2018-06-03 0",
      "EventMonth": "June",
      "EventDay": 3,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1502,
      "EVENTNAME": "NSW Blues vs. Queensland Maroons",
      "DESCR": "Carparks only open to Media, Emergency Vehicles and Pass holders Carpark Gate 3 Closed 20:30 Carpark Gate 5 Closed Carpark Gate 6 Closed Carpark Gate 7 Closed Supplementary Light on 16:30 Light towers on at 19:56 Light Towers off at 23:00 Game Finishes 22:07",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "00:00.5",
      "DAYID": 6,
      "YEARID": 21,
      "WEATHERTEMP": 12.2,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 1018,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 18,
      "AWAYTEAMID": 19,
      "TOTALATT": 87122,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 45,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 80000,
      "FINBUDGATT": 80000,
      "EventNameDate": "NSW Blues vs. Queensland Maroons - 2018-06-06 0",
      "EventMonth": "June",
      "EventDay": 6,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1503,
      "EVENTNAME": "Melbourne vs. Collingwood",
      "DESCR": "Big Freeze 4 pre-event Carpark Gate 3 Closed to Public 12:55 Disability entry Closed 13:40   Carpark Gate 5 Closed 14:40 Carpark Gate 6 Closed 13:47 Carpark Gate 7 Closed 14:15 Supplementary Lights on at 14:50 Light Towers on at 14:50 Light Towers off at 18:40 Game Finished 17:55",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.8",
      "DAYID": 4,
      "YEARID": 24,
      "WEATHERTEMP": 16,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 15,
      "VENUEID": 1,
      "ATTENDANCEID": 1019,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 4,
      "TOTALATT": 83518,
      "EVENTCATEGORYID": 2,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 79000,
      "FINBUDGATT": 79000,
      "EventNameDate": "Melbourne vs. Collingwood - 2018-06-11 0",
      "EventMonth": "June",
      "EventDay": 11,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1504,
      "EVENTNAME": "Hawthorn vs. Adelaide Crows",
      "DESCR": "Car Park Gate 3 Closed 18:30 for Public; Closed 20:10 for disability parking Car Park Gate 5 Closed 20:20 Car Park Gate 6 Closed 20:00 Car Park Gate 7 Closed 20:30 Supplementary Lights on 17:20 Light Towers On at 18:25 Light Towers Off 22:30 Game Finished 21:55",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "25:00.7",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 9.2,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 12,
      "VENUEID": 1,
      "ATTENDANCEID": 1020,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 8,
      "AWAYTEAMID": 1,
      "TOTALATT": 26693,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 35000,
      "FINBUDGATT": 35000,
      "EventNameDate": "Hawthorn vs. Adelaide Crows - 2018-06-16 0",
      "EventMonth": "June",
      "EventDay": 16,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1505,
      "EVENTNAME": "Geelong Cats vs. Richmond",
      "DESCR": "Carparks reduced to 30%due to rain (750 cars) Carpark Gate 3 closed to public12:35 to mobility impaired 13:55 Carpark Gate 5 Closed 13:40 Carpark Gate 6 Closed 13:18 Carpark Gate 7 Closed 12:40 Supplementary Lights on at 15:00 Light Towers on at 15:00 Light Towers off at 18:30 Game Finished 17:54",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.8",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 12.5,
      "WEATHERRAIN": 6,
      "WEATHERWIND": 15,
      "VENUEID": 1,
      "ATTENDANCEID": 1021,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 7,
      "AWAYTEAMID": 12,
      "TOTALATT": 46423,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 60000,
      "FINBUDGATT": 60000,
      "EventNameDate": "Geelong Cats vs. Richmond - 2018-06-17 0",
      "EventMonth": "June",
      "EventDay": 17,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1506,
      "EVENTNAME": "Collingwood vs. Carlton",
      "DESCR": "Curtain Raiser Under 18's National Championships Vic Country v Vic Metro game time 12:10 Final Score - Metro by 26 points Vic Country 8-10-58 Vic Metro    13-6-84 Car Park Gate 3 closed 14:15hrs Car Park Gate 5 closed 14:52hrs Car Park Gate 6 closed 16:14hrs Car Park Gate 7 closed 15:14hrs Supplementary Lights on 14:40hrs Light Towers on 15:50hrs Light Towers off 18:30hrs Game over 17:48hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.0",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 12.3,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 9,
      "VENUEID": 1,
      "ATTENDANCEID": 1022,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 3,
      "TOTALATT": 53706,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 45000,
      "FINBUDGATT": 45000,
      "EventNameDate": "Collingwood vs. Carlton - 2018-06-24 0",
      "EventMonth": "June",
      "EventDay": 24,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1507,
      "EVENTNAME": "Carlton vs. Port Adelaide",
      "DESCR": "Car Park - 70% capacity Carpark Gate 3 closed 13:10 Carpark Gate 5 closed 14:00 Carpark Gate 6 closed 13:25 Carpark Gate 7 closed 14:00 Supplementary Light on at 13:00 Light Towers on at 14:45 Light Towers off at 16:40 Game Finished 16:18",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "45:00.8",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 12.3,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 12,
      "VENUEID": 1,
      "ATTENDANCEID": 1023,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 3,
      "AWAYTEAMID": 11,
      "TOTALATT": 26562,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 26500,
      "FINBUDGATT": 26500,
      "EventNameDate": "Carlton vs. Port Adelaide - 2018-06-30 0",
      "EventMonth": "June",
      "EventDay": 30,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1508,
      "EVENTNAME": "Melbourne vs. St Kilda",
      "DESCR": "Car Park Gate 3 closed 12:37hrs Car Park Gate 5 closed 12:55hrs Car Park Gate 6 closed 12:37hrs Car Park Gate 7 closed 14:15hrs Supplementary Lights on 14:45hrs Light Towers not turned on. Game over 15:48hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.0",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 13.5,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 6,
      "VENUEID": 1,
      "ATTENDANCEID": 1024,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 13,
      "TOTALATT": 38910,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 40000,
      "FINBUDGATT": 40000,
      "EventNameDate": "Melbourne vs. St Kilda - 2018-07-01 0",
      "EventMonth": "July",
      "EventDay": 1,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1509,
      "EVENTNAME": "Richmond vs. Adelaide Crows",
      "DESCR": "Car Park  Gate 3  Closed 19:40 Car Park  Gate 5  Closed  20:45 Car Park  Gate 6  Closed 19:25 Car Park  Gate 7  Closed 20:45 Supplementary Lights on at 17:30 Light Towers On at 18:50 Light Towers Off at  23:00 Game Finished at 22:20",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.9",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 12.5,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 15,
      "VENUEID": 1,
      "ATTENDANCEID": 1025,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 1,
      "TOTALATT": 54934,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 57000,
      "FINBUDGATT": 57000,
      "EventNameDate": "Richmond vs. Adelaide Crows - 2018-07-06 0",
      "EventMonth": "July",
      "EventDay": 6,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1510,
      "EVENTNAME": "Essendon vs. Collingwood",
      "DESCR": "Carpark Gate 3 Closed 14:23 Carpark Gate 5 Closed 15:00 Carpark Gate 6 Closed 14:20 Carpark Gate 7 Closed 15:20 Supplementary Lights on at 14:45 Light Towers on at 14:45 Light Towers off at 18:35 Game Finished 17:51",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.9",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 12.5,
      "WEATHERRAIN": 1,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 1026,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 5,
      "AWAYTEAMID": 4,
      "TOTALATT": 69868,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 74000,
      "FINBUDGATT": 74000,
      "EventNameDate": "Essendon vs. Collingwood - 2018-07-08 0",
      "EventMonth": "July",
      "EventDay": 8,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1511,
      "EVENTNAME": "Melbourne vs. Western Bulldogs",
      "DESCR": "Carpark Gate 3 closed at 16:20 Carpark Gate 5 closed at 17:30 Carpark Gate 6 closed at 16:10 Carpark Gate 7 closed at 17:45 Supplementary Lights on at 16:00 Light towers on at 16:00 Light towers off at 20:00 Game Finished 19:06",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "35:00.9",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 11.9,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 13,
      "VENUEID": 1,
      "ATTENDANCEID": 1027,
      "DAYNIGHTID": 3,
      "MatchTimeName": "Twilight",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 16,
      "TOTALATT": 31053,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 34000,
      "FINBUDGATT": 34000,
      "EventNameDate": "Melbourne vs. Western Bulldogs - 2018-07-14 0",
      "EventMonth": "July",
      "EventDay": 14,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1512,
      "EVENTNAME": "Collingwood vs. West Coast Eagles",
      "DESCR": "Car Park Gate 3 closed 12:55hrs Car Park Gate 5 closed 12:58hrs Car Park Gate 6 closed 12:30hrs Car Park Gate 7 closed 13:35hrs Light Towers not turned on Game over 15:38hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.3",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 13.2,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 24,
      "VENUEID": 1,
      "ATTENDANCEID": 1028,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 15,
      "TOTALATT": 53439,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 45000,
      "FINBUDGATT": 45000,
      "EventNameDate": "Collingwood vs. West Coast Eagles - 2018-07-15 0",
      "EventMonth": "July",
      "EventDay": 15,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1513,
      "EVENTNAME": "Collingwood vs. North Melbourne",
      "DESCR": "Car Park Gate 3 closed 13:10hrs Car Park Gate 5 closed 13:48hrs Car Park Gate 6 closed 13:30hrs Car Park Gate 7 closed 14:15hrs Supplementary lights on 13:50hrs Light Towers on 14:51hrs Light Towers off 16:40hrs Game over 16:19hrs",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "45:00.3",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 12.7,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 13,
      "VENUEID": 1,
      "ATTENDANCEID": 1029,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 9,
      "TOTALATT": 50393,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 53000,
      "FINBUDGATT": 53000,
      "EventNameDate": "Collingwood vs. North Melbourne - 2018-07-21 0",
      "EventMonth": "July",
      "EventDay": 21,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1514,
      "EVENTNAME": "Richmond vs. Collingwood",
      "DESCR": "Carpark Gate 3 closed 14:30 Carpark Gate 5 closed 14:30 Carpark Gate 6 closed 12:20 Carpark Gate 7 closed 12:52 Supplementary Lights: never turned on Light towers: never turned on Game Finished: 16:20",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "45:00.9",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 17.8,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 17,
      "VENUEID": 1,
      "ATTENDANCEID": 1030,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 4,
      "TOTALATT": 88180,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 86000,
      "FINBUDGATT": 86000,
      "EventNameDate": "Richmond vs. Collingwood - 2018-07-28 0",
      "EventMonth": "July",
      "EventDay": 28,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1515,
      "EVENTNAME": "Richmond vs. Geelong Cats",
      "DESCR": "Carpark Gate 3 Closed 19:30 Carpark Gate 5 Closed 20:23 Carpark Gate 6 Closed 19:25 Carpark Gate 7 Closed 20:10 Supplementary lights on at  17:30 Light Towers on at 18:40 Light Towers off at 11:10 Game Finished at 22:24",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.1",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 10.6,
      "WEATHERRAIN": 2,
      "WEATHERWIND": 13,
      "VENUEID": 1,
      "ATTENDANCEID": 1031,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 7,
      "TOTALATT": 67054,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 73000,
      "FINBUDGATT": 73000,
      "EventNameDate": "Richmond vs. Geelong Cats - 2018-08-03 0",
      "EventMonth": "August",
      "EventDay": 3,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1516,
      "EVENTNAME": "Hawthorn vs. Essendon",
      "DESCR": "Carpark Gate 3 closed 13:30 Carpark Gate 5 closed 13:35 Carpark Gate 6 closed 13:04 Carpark Gate 7 closed 14:20 Supplementary lights on 13:15 Light Towers on at 14:05 Light Towers off at 17:00 Game Finished 16:24",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "45:00.3",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 13.7,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 17,
      "VENUEID": 1,
      "ATTENDANCEID": 1032,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 8,
      "AWAYTEAMID": 5,
      "TOTALATT": 68857,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 69000,
      "FINBUDGATT": 69000,
      "EventNameDate": "Hawthorn vs. Essendon - 2018-08-04 0",
      "EventMonth": "August",
      "EventDay": 4,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1517,
      "EVENTNAME": "Melbourne vs. Gold Coast Suns",
      "DESCR": "Carpark Gate 3 closed 15:20 Carpark Gate 5 closed 15:30  Carpark Gate 6 closed 15:00 Carpark Gate 7 closed 16:20 Supplementary Lights on at 15:55 Light Towers on at 15:55 Light Towers off at 18:30 Game Over 17:49",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.3",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 16.9,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 26,
      "VENUEID": 1,
      "ATTENDANCEID": 1033,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 40,
      "TOTALATT": 23072,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 27000,
      "FINBUDGATT": 27000,
      "EventNameDate": "Melbourne vs. Gold Coast Suns - 2018-08-05 0",
      "EventMonth": "August",
      "EventDay": 5,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1518,
      "EVENTNAME": "Hawthorn vs. Geelong Cats",
      "DESCR": "Carpark Gate 3 closed 13:00 Carpark Gate 5 closed 13:30 Carpark Gate 6 closed 12:38 Carpark Gate 7 closed 14:13 Supplementary lights on at 13:25 Light Towers on at 14:45 Light Towers off at 17:00 Game Over at 16:16",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "45:00.6",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 12.6,
      "WEATHERRAIN": 1,
      "WEATHERWIND": 9,
      "VENUEID": 1,
      "ATTENDANCEID": 1034,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 8,
      "AWAYTEAMID": 7,
      "TOTALATT": 59529,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 55000,
      "FINBUDGATT": 55000,
      "EventNameDate": "Hawthorn vs. Geelong Cats - 2018-08-11 0",
      "EventMonth": "August",
      "EventDay": 11,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1519,
      "EVENTNAME": "Melbourne vs. Sydney Swans",
      "DESCR": "Carpark capacity reduced to 75% Carpark Gate 3 closed All at 15:20, 12:55 to Public Carpark Gate 5 closed 14:50 Carpark Gate 6 closed 14:20 Carpark Gate 7 closed 15:20 Supplementary Lights on at 14:50 Light Towers on at 14:50 Light Towers off at 18:40 Game over at 17:52",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.9",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 13.2,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 15,
      "VENUEID": 1,
      "ATTENDANCEID": 1035,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 14,
      "TOTALATT": 51424,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 49000,
      "FINBUDGATT": 49000,
      "EventNameDate": "Melbourne vs. Sydney Swans - 2018-08-12 0",
      "EventMonth": "August",
      "EventDay": 12,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1520,
      "EVENTNAME": "Richmond vs. Essendon",
      "DESCR": "Carpark Gate 3 Closed 19:00 Carpark Gate 5 Closed 19:35 Carpark Gate 6 Closed 18:57 Carpark Gate 7 Closed 19:24 Supplementary lights on at 17:30 Light Towers on at 18:50 Light Towers off at 23:00 Game Finished 22:16",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.7",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 12.7,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 20,
      "VENUEID": 1,
      "ATTENDANCEID": 1036,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 5,
      "TOTALATT": 76424,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 78000,
      "FINBUDGATT": 78000,
      "EventNameDate": "Richmond vs. Essendon - 2018-08-17 0",
      "EventMonth": "August",
      "EventDay": 17,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1521,
      "EVENTNAME": "Collingwood vs. Port Adelaide",
      "DESCR": "Curtain Raiser Herald Sun Shield Boys Division 1 Grand Final St Bernards College 10-10-70 def St Patricks College 5-9-39 Carpark capacity reduced by 10% Carpark Gate 3 Closed 13:20 Carpark Gate 5 Closed 13:46 Carpark Gate 6 Closed 13:05 Carpark Gate 7 Closed 13:38 Supplementary lights on at 13:05 Light Towers on at 13:15 Light Towers off at 16:45 Game Finished 16:14",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "45:00.4",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 10.8,
      "WEATHERRAIN": 2,
      "WEATHERWIND": 17,
      "VENUEID": 1,
      "ATTENDANCEID": 1037,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 11,
      "TOTALATT": 46286,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 45000,
      "FINBUDGATT": 45000,
      "EventNameDate": "Collingwood vs. Port Adelaide - 2018-08-18 0",
      "EventMonth": "August",
      "EventDay": 18,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1522,
      "EVENTNAME": "Richmond vs. Western Bulldogs",
      "DESCR": "Carpark Gate 3 Closed 13:20 Carpark Gate 5 Closed 13:58 Carpark Gate 6 Closed 13:15 Carpark Gate 7 Closed 14:50 Supplementary Lights 16:05  Game Finished 16:40",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "10:00.3",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 14.1,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 12,
      "VENUEID": 1,
      "ATTENDANCEID": 1038,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 16,
      "TOTALATT": 56998,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 60000,
      "FINBUDGATT": 60000,
      "EventNameDate": "Richmond vs. Western Bulldogs - 2018-08-25 0",
      "EventMonth": "August",
      "EventDay": 25,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1523,
      "EVENTNAME": "Melbourne vs. GWS Giants",
      "DESCR": "Carpark Gate 3 Closed 14:30 Carpark Gate 5 Closed 15:08 Carpark Gate 6 Closed 14:30 Carpark Gate 7 Closed 16:10 Supplementary Lights on at 15:40 Light Towers on at 15:40 Light Towers off at 18:30 Game Finished 17:47",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.5",
      "DAYID": 3,
      "YEARID": 24,
      "WEATHERTEMP": 13.9,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 9,
      "VENUEID": 1,
      "ATTENDANCEID": 1039,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 41,
      "TOTALATT": 37285,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 1,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 37000,
      "FINBUDGATT": 37000,
      "EventNameDate": "Melbourne vs. GWS Giants - 2018-08-26 0",
      "EventMonth": "August",
      "EventDay": 26,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 0
    },
    {
      "EVENTID": 1524,
      "EVENTNAME": "Richmond vs. Hawthorn",
      "DESCR": "Carparks Closed to Public.  Carpark Gate 3 Mobility Impaired and Pass holders only Closed 20:00 Carpark Gate 5 Not Open Carpark Gate 6 Not Open Carpark Gate 7 Not Open Supplementary Lights on 16:30 Light Towers on at 18:20 Light Towers off at 23:00 Game Finished 21:55",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "20:00.9",
      "DAYID": 7,
      "YEARID": 24,
      "WEATHERTEMP": 12,
      "WEATHERRAIN": 3,
      "WEATHERWIND": 5,
      "VENUEID": 1,
      "ATTENDANCEID": 1040,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 8,
      "TOTALATT": 91446,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 2,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 94000,
      "FINBUDGATT": 94000,
      "EventNameDate": "Richmond vs. Hawthorn - 2018-09-06 0",
      "EventMonth": "September",
      "EventDay": 6,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 1
    },
    {
      "EVENTID": 1525,
      "EVENTNAME": "Melbourne vs. Geelong Cats",
      "DESCR": "Carparks Mobility impaired and pass holders only Carpark Gate 3 closed 20:30 Carpark Gate 5 Not Open Carpark Gate 6 Not Open Carpark Gate 7 Not Open Supplementary Light on at 17:00 Light Towers on at 18:25 Light Towers off at 23:15 Game Finished 22:18",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.6",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 10,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 4,
      "VENUEID": 1,
      "ATTENDANCEID": 1041,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 10,
      "AWAYTEAMID": 7,
      "TOTALATT": 91767,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 43,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 90000,
      "FINBUDGATT": 90000,
      "EventNameDate": "Melbourne vs. Geelong Cats - 2018-09-07 0",
      "EventMonth": "September",
      "EventDay": 7,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 1
    },
    {
      "EVENTID": 1526,
      "EVENTNAME": "Hawthorn vs. Melbourne",
      "DESCR": "Carparks Closed to public. Disability and Pass holders only. Carpark Gate 3 Closed 20:30 Carpark Gate 5 Not Open Carpark Gate 6 Not Open Carpark Gate 6 Not Open Carpark Gate 7 Not Open Supplementary Lights 17:30 Light Towers on at 18:50 Light Towers off at 23:15 Game Finished 22:20",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.3",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 18.4,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 13,
      "VENUEID": 1,
      "ATTENDANCEID": 1042,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 8,
      "AWAYTEAMID": 10,
      "TOTALATT": 90152,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 3,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 93500,
      "FINBUDGATT": 93500,
      "EventNameDate": "Hawthorn vs. Melbourne - 2018-09-14 0",
      "EventMonth": "September",
      "EventDay": 14,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 1
    },
    {
      "EVENTID": 1527,
      "EVENTNAME": "Collingwood vs. GWS Giants",
      "DESCR": "Carpark Gate 3 Closed 18:33 Carpark Gate 5 Closed 20:20 Carpark Gate 6 Closed 18:25 Carpark Gate 7 Closed 20:20 Supplementary Lights 16:30 Light Towers on at 18:25 Light Towers off at 22:45 Game Finished 21:50",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "25:00.8",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 6.5,
      "WEATHERRAIN": 2,
      "WEATHERWIND": 13,
      "VENUEID": 1,
      "ATTENDANCEID": 1043,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 4,
      "AWAYTEAMID": 41,
      "TOTALATT": 72504,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 3,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 73500,
      "FINBUDGATT": 73500,
      "EventNameDate": "Collingwood vs. GWS Giants - 2018-09-15 0",
      "EventMonth": "September",
      "EventDay": 15,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 1
    },
    {
      "EVENTID": 1528,
      "EVENTNAME": "Richmond vs. Collingwood",
      "DESCR": "Carparks Closed to Public. Disability and Pass holders only. Carpark Gate 3 Closed 20:10 Carpark Gate 5 Not open Carpark Gate 6 Not open Carpark Gate 7 Not open Supplimentary lights on at 17:00 Light towers on at 18:50 Light towers off at 23:15 Game Finished 22:24",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "50:00.1",
      "DAYID": 1,
      "YEARID": 24,
      "WEATHERTEMP": 13.8,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 0,
      "VENUEID": 1,
      "ATTENDANCEID": 1044,
      "DAYNIGHTID": 2,
      "MatchTimeName": "Night",
      "HOMETEAMID": 12,
      "AWAYTEAMID": 4,
      "TOTALATT": 94959,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 4,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 97000,
      "FINBUDGATT": 97000,
      "EventNameDate": "Richmond vs. Collingwood - 2018-09-21 0",
      "EventMonth": "September",
      "EventDay": 21,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 1
    },
    {
      "EVENTID": 1529,
      "EVENTNAME": "West Coast Eagle vs. Collingwood",
      "DESCR": "Curtain Raiser match 10:00 NAB AFL All Stars U/18s Team Riewoldt 8-10-58 lost to Team Bartel 15-10-100.  Carparks Closed to Public. Pass holders and Disability parking only. Gate 3 Not Open Gate 5 Closed 14:00 Gate 6 Not Open Gate 7 Not Open Supplementary Lights on at 14:40 Light Towers on at 14:40 Light Towers off at 19:00 Game Finished 17:12 Premiership Party in Evening",
      "EVENTDATE": "00:00.0",
      "EVENTTIME": "30:00.7",
      "DAYID": 2,
      "YEARID": 24,
      "WEATHERTEMP": 12.4,
      "WEATHERRAIN": 0,
      "WEATHERWIND": 11,
      "VENUEID": 1,
      "ATTENDANCEID": 1045,
      "DAYNIGHTID": 1,
      "MatchTimeName": "Day",
      "HOMETEAMID": 15,
      "AWAYTEAMID": 4,
      "TOTALATT": 100022,
      "EVENTCATEGORYID": 1,
      "ISEVENTACTIVE": "Y",
      "EVENTTYPECLASSID": 5,
      "PARENTEVENTID": "NULL",
      "EVENTSESTATT": 100024,
      "FINBUDGATT": 100024,
      "EventNameDate": "West Coast Eagle vs. Collingwood - 2018-09-29 0",
      "EventMonth": "September",
      "EventDay": 29,
      "EventYearName": 2018,
      "FinancialYear": 2019,
      "IsEventaFinal": 1
    }
  ]